jobs:
  ################################################################################
  # Initialization - Generate the VSTS build matrix
  ################################################################################
- job: GenerateMatrices
  pool: # linuxAmd64Pool
    name: DotNet-Build
    demands: agent.os -equals linux
  steps:
  - template: ../steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) generateBuildMatrix
      --manifest $(manifest) --type build --os-type '*' --architecture '*' $(imageBuilder.generateMatrixQueueArgs)
    name: buildMatrix
  - script: >
      $(runImageBuilderCmd) generateBuildMatrix
      --manifest $(manifest) --type test --os-type '*' --architecture '*' $(imageBuilder.generateMatrixQueueArgs)
    name: testMatrix
  - script: >
      $(runImageBuilderCmd) generateBuildMatrix
      --manifest $(manifest) --type publish --os-type '*' --architecture '*' $(imageBuilder.generateMatrixQueueArgs)
    name: publishMatrix
  - template: ../steps/cleanup-docker-linux.yml

  ################################################################################
  # Build Images
  ################################################################################
- template: build-images.yml
  parameters:
    name: Build_WindowsServerCoreLtsc2016_amd64
    pool: # windows1607Amd64Pool
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
    matrix: dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixWindowsservercoreLtsc2016Amd64']
- template: build-images.yml
  parameters:
    name: Build_WindowsServerCore1709_amd64
    pool: # windows1709Amd64Pool
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS3
    matrix: dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixWindowsservercore1709Amd64']
- template: build-images.yml
  parameters:
    name: Build_WindowsServerCore1803_amd64
    pool: # windows1803Amd64Pool
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
    matrix: dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixWindowsservercore1803Amd64']
- template: build-images.yml
  parameters:
    name: Build_WindowsServerCoreLtsc2019_amd64
    pool: # windows1809Amd64
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
    matrix: dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixWindowsservercoreLtsc2019Amd64']

  ################################################################################
  # Test Images
  ################################################################################
- template: test-images.yml
  parameters:
    name: Test_WindowsServerCoreLtsc2016_amd64
    buildDependencies: Build_WindowsServerCoreLtsc2016_amd64
    pool: # windows1607Amd64Pool
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
    matrix: dependencies.GenerateMatrices.outputs['testMatrix.testMatrixWindowsservercoreLtsc2016Amd64']
- template: test-images.yml
  parameters:
    name: Test_WindowsServerCore1709_amd64
    buildDependencies: Build_WindowsServerCore1709_amd64
    pool: # windows1709Amd64Pool
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS3
    matrix: dependencies.GenerateMatrices.outputs['testMatrix.testMatrixWindowsservercore1709Amd64']
- template: test-images.yml
  parameters:
    name: Test_WindowsServerCore1803_amd64
    buildDependencies: Build_WindowsServerCore1803_amd64
    pool: # windows1803Amd64Pool
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
    matrix: dependencies.GenerateMatrices.outputs['testMatrix.testMatrixWindowsservercore1803Amd64']
- template: test-images.yml
  parameters:
    name: Test_WindowsServerCoreLtsc2019_amd64
    buildDependencies: Build_WindowsServerCoreLtsc2019_amd64
    pool: # windows1809Amd64
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
    matrix: dependencies.GenerateMatrices.outputs['testMatrix.testMatrixWindowsservercoreLtsc2019Amd64']

  ################################################################################
  # Publish Images
  ################################################################################
- template: copy-images.yml
  parameters:
    pool: # linuxAmd64Pool
      name: DotNet-Build
      demands: agent.os -equals linux
    matrix: dependencies.GenerateMatrices.outputs['publishMatrix.publishMatrix']

- template: publish-finalize.yml
  parameters:
    pool: # linuxAmd64Pool
      name: DotNet-Build
      demands: agent.os -equals linux
