parameters:
  name: null
  pool: {}
  matrix: {}
jobs:
- job: ${{ parameters.name }}
  condition: and(succeeded(), ${{ parameters.matrix }})
  dependsOn: GenerateBuildMatrix
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  timeoutInMinutes: 330
  variables:
    osVersion: ${{ parameters.osVersion }}
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      imageBuilderBuildArgs: >
        --registry-override $(acr.server)
        --repo-prefix $(stagingRepoPrefix)
        --push
        --username $(acr.userName)
        --password $(BotAccount-dotnet-docker-acr-bot-password)
        $(imageBuilder.queueArgs)
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      imageBuilderBuildArgs: $(imageBuilder.queueArgs)
  steps:
  - template: ../steps/init-docker-windows.yml
  - script:  >
      $(runImageBuilderCmd) build 
      --manifest $(manifest)
      $(imageBuilderPaths)
      --os-type $(osType)
      --os-version "$(osVersion)"
      --architecture $(architecture)
      --retry
      $(imageBuilderBuildArgs)
    displayName: Build Images
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - template: ../steps/test-images-windows-client.yml
  - template: ../steps/cleanup-docker-windows.yml
