blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://stackoverflow.com/questions/tagged/.net
    about: Is your issue perhaps more of a question? Please post questions on Stack Overflow.
  - name: Issue with .NET Framework, ASP.NET or WCF
    url: https://developercommunity.visualstudio.com/spaces/61/index.html
    about: Please report problems relating to the .NET Framework, ASP.NET or WCF on the .NET Developer Community website.
  - name: Issue with Visual Studio Tools for Docker
    url: https://github.com/microsoft/dockertools/issues
    about: Please open issues relating to the Visual Studio Tools for Docker in microsoft/dockertools.
  - name: Issue with Microsoft Container Registry (MCR)
    url: https://github.com/microsoft/containerregistry/issues
    about: Please open issues relating to the Microsoft Container Registry (MCR) in microsoft/containerregistry.
  - name: Issue with Windows containers
    url: https://github.com/Microsoft/Windows-Containers/issues
    about: Please open issues relating to Windows containers in microsoft/Windows-Containers.
