aliveStatusCodes:
  - 200
  - 406
dirs:
  - .
  - .github
excludedDirs:
  - eng/readme-templates
ignorePatterns:
  - pattern: "^https://dotnetbinaries.blob.core.windows.net/dockerassets"
  - pattern: "^https://github.com/dotnet/release/blob/main/.github/ISSUE_TEMPLATE/dotnet-fx-docker-servicing-release.md"
useGitIgnore: true
