parameters:
  buildMatrixType: platformDependencyGraph
  testMatrixType: platformVersionedOs
  customBuildLegGrouping: ""
  
stages:

  ################################################################################
  # Build Images
  ################################################################################
- stage: Build
  condition: or(eq(variables['singlePhase'], ''), eq(variables['singlePhase'], 'build'))
  jobs:
  - template: ../jobs/generate-matrix.yml
    parameters:
      matrixType: ${{ parameters.buildMatrixType }}
      name: GenerateBuildMatrix
      customBuildLegGrouping: ${{ parameters.customBuildLegGrouping }}

  - template: ../jobs/build-images.yml
    parameters:
      name: Build_WindowsServerCoreLtsc2016_amd64
      pool: # windows1607Amd64Pool
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
      matrix: dependencies.GenerateBuildMatrix.outputs['${{ format('matrix.{0}MatrixWindowsservercoreLtsc2016Amd64', parameters.buildMatrixType) }}']
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_WindowsServerCore1803_amd64
      pool: # windows1803Amd64Pool
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
      matrix: dependencies.GenerateBuildMatrix.outputs['${{ format('matrix.{0}MatrixWindowsservercore1803Amd64', parameters.buildMatrixType) }}']
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_WindowsServerCoreLtsc2019_amd64
      pool: # windows1809Amd64
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
      matrix: dependencies.GenerateBuildMatrix.outputs['${{ format('matrix.{0}MatrixWindowsservercoreLtsc2019Amd64', parameters.buildMatrixType) }}']

- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    ################################################################################
    # Test Images
    ################################################################################
  - stage: Test
    dependsOn: Build
    condition: "
      and(
        not(contains(variables['manifest'], 'samples')),
        or(
          and(
            succeeded(),
            eq(variables['singlePhase'], '')),
          eq(variables['singlePhase'], 'test')))"
    jobs:
    - template: ../jobs/generate-matrix.yml
      parameters:
        matrixType: ${{ parameters.testMatrixType }}
        name: GenerateTestMatrix

    - template: ../jobs/test-images.yml
      parameters:
        name: Test_WindowsServerCoreLtsc2016_amd64
        buildDependencies: Build_WindowsServerCoreLtsc2016_amd64
        pool: # windows1607Amd64Pool
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
        matrix: dependencies.GenerateTestMatrix.outputs['${{ format('matrix.{0}MatrixWindowsservercoreLtsc2016Amd64', parameters.testMatrixType) }}']
    - template: ../jobs/test-images.yml
      parameters:
        name: Test_WindowsServerCore1803_amd64
        buildDependencies: Build_WindowsServerCore1803_amd64
        pool: # windows1803Amd64Pool
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
        matrix: dependencies.GenerateTestMatrix.outputs['${{ format('matrix.{0}MatrixWindowsservercore1803Amd64', parameters.testMatrixType) }}']
    - template: ../jobs/test-images.yml
      parameters:
        name: Test_WindowsServerCoreLtsc2019_amd64
        buildDependencies: Build_WindowsServerCoreLtsc2019_amd64
        pool: # windows1809Amd64
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
        matrix: dependencies.GenerateTestMatrix.outputs['${{ format('matrix.{0}MatrixWindowsservercoreLtsc2019Amd64', parameters.testMatrixType) }}']

    ################################################################################
    # Publish Images
    ################################################################################
  - stage: Publish
    dependsOn: Test
    condition: "
      or(
        and(
          eq(variables['singlePhase'], ''),
          or(
            succeeded(),
            and(
              contains(variables['manifest'], 'samples'),
              succeeded('Build')))),
        eq(variables['singlePhase'], 'publish'))"
    jobs:
    - template: ../jobs/publish.yml
      parameters:
          pool: # linuxAmd64Pool
            name: Hosted Ubuntu 1604
