{{

    _ ARGS:
        usePowerShell: whether to use PowerShell to download and remove files ^

    set sdkVersion to when(PRODUCT_VERSION = "4.8.1", "4.8.1", "4.8")

}}# Install VS Build Tools{{
if ARGS.usePowerShell:
&& powershell -Command `
    $ProgressPreference = 'SilentlyContinue'; `
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; `
    Invoke-WebRequest `
        -UseBasicParsing `
        -Uri {{VARIABLES["vs|buildToolsUrl"]}} `
        -OutFile vs_BuildTools.exe `^
else:
&& curl -fSLo vs_BuildTools.exe {{VARIABLES["vs|buildToolsUrl"]}} `}}
&& start /w vs_BuildTools @^ `
    --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" @^ `
    --add Microsoft.Component.ClickOnce.MSBuild @^ `
    --add Microsoft.Net.Component.{{sdkVersion}}.SDK @^ `
    --add Microsoft.NetCore.Component.Runtime.8.0 @^ `
    --add Microsoft.NetCore.Component.Runtime.9.0 @^ `
    --add Microsoft.NetCore.Component.SDK @^ `
    --add Microsoft.VisualStudio.Component.NuGet.BuildTools @^ `
    --add Microsoft.VisualStudio.Component.WebDeploy @^ `
    --add Microsoft.VisualStudio.Web.BuildTools.ComponentGroup @^ `
    --add Microsoft.VisualStudio.Workload.MSBuildTools @^ `
    --quiet --norestart --nocache --wait `
&& powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
&& del vs_BuildTools.exe `