# This pipelines builds all projects in the repository outside of Dockerfiles so that the artifacts
# can be scanned by SDL steps.  SDL steps do not scan artifacts that are built within Dockerfiles.
trigger:
  branches:
    include:
    - main
    - dev
pr: none

parameters:
# Setting cgDryRun will run CG but not submit the results
- name: cgDryRun
  type: boolean
  default: false
  displayName: CG Dry Run

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: cgBuildGrepArgs
  value: -v -e 'samples/' -e 'tests/'
# Skip CG detection (for debugging project builds, etc.)
- name: skipComponentGovernanceDetection
  value: false

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    cgDryRun: ${{ parameters.cgDryRun }}
    stages:
    - stage: CgDetection
      displayName: CG Detection
      jobs:
      - template: /eng/common/templates/jobs/cg-build-projects.yml@self
        parameters:
          cgDryRun: ${{ parameters.cgDryRun }}
