trigger: none
pr: none

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.json
- name: mcrImageIngestionTimeout
  value: "00:30:00"

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    windowsAmdBuildJobTimeout: 240
    windowsAmdTestJobTimeout: 90
