trigger: none
pr:
  branches:
    include:
    - main
    - master
    - dev
  paths:
    exclude:
    - .github/*
    - README*
    - samples/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.json

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build
    windowsAmdBuildJobTimeout: 330
