trigger: none
pr:
- master

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.runtime-sdk.json
- name: repoTestArgs
  value: "-TestCategory runtime-sdk"
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      windowsAmdBuildJobTimeout: 180
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
      customBuildLegGrouping: pr-build
      windowsAmdBuildJobTimeout: 360
