trigger: none
pr:
- master
- dev

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.json
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      windowsAmdBuildJobTimeout: 150
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
      customBuildLegGrouping: pr-build
      windowsAmdBuildJobTimeout: 300
