trigger: none
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

parameters:
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test or publish images that were built in a different pipeline run. When
    building new images, leave this value alone.
  type: string
  default: $(Build.BuildId)

variables:
- template: /eng/pipelines/variables/common.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
- name: manifest
  value: manifest.json
- name: mcrImageIngestionTimeout
  value: "00:30:00"

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(internal-mirror.serviceConnectionName)
    - name: $(build.serviceConnectionName)
    - name: $(publish.serviceConnectionName)
    - name: $(kusto.serviceConnectionName)
    - name: $(marStatus.serviceConnectionName)
    stages:
    - template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        windowsAmdBuildJobTimeout: 240
        windowsAmdTestJobTimeout: 90
