trigger: none
pr: none
variables:
- template: variables/common.yml
- name: manifest
  value: manifest.samples.json
- name: imageInfoVariant
  value: "-samples"
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
      customBuildLegGrouping: pr-build
