trigger: none
pr:
  branches:
    include:
    - main
    - dev
  paths:
    exclude:
    - .github/*
    - README*
    - samples/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: manifest
  value: manifest.json

stages:
- template: /eng/common/templates/stages/dotnet/publish-config-nonprod.yml@self
  parameters:
    stagesTemplate: /eng/pipelines/stages/dotnet-framework-base.yml@self
    stagesTemplateParameters:
      versionsRepoRef: VersionsRepo
