trigger: none
pr: none
variables:
- group: DotNet-Maestro
- template: /eng/pipelines/variables/common.yml@self
- name: manifest
  value: manifest.json

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - stage: UpdateReadmes
      displayName: Update Readmes
      jobs:
      - job: UpdateReadmes
        displayName: Update Readmes
        steps:
        - template: /eng/common/templates/steps/init-docker-linux.yml@self
        - template: /eng/common/templates/steps/publish-readmes.yml@self
        - template: /eng/common/templates/steps/cleanup-docker-linux.yml@self