trigger: none
pr: none
variables:
- group: DotNet-Maestro
- template: /eng/pipelines/variables/common.yml@self
- name: manifest
  value: manifest.json
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: UpdateReadmes
      displayName: Update Readmes
      jobs:
      - job: UpdateReadmes
        displayName: Update Readmes
        pool:
          name: NetCore1ESPool-Internal
          image: 1es-ubuntu-2204
          os: linux
        steps:
        - template: /eng/common/templates/steps/init-docker-linux.yml@self
        - template: /eng/common/templates/steps/publish-readmes.yml@self
        - template: /eng/common/templates/steps/cleanup-docker-linux.yml@self