FROM microsoft/dotnet-framework:4.7.2-sdk AS build
WORKDIR /app
COPY WcfServiceWebApp/. ./WcfServiceWebApp/
WORKDIR /app/WcfServiceWebApp
RUN msbuild

FROM microsoft/wcf:4.7.2 AS runtime
WORKDIR /inetpub/wwwroot
COPY --from=build /app/WcfServiceWebApp/ ./