FROM microsoft/dotnet-framework:4.7.2-sdk AS build
WORKDIR /app
COPY WcfClient/. ./WcfClient/
WORKDIR /app/WcfClient
RUN msbuild

FROM microsoft/dotnet-framework:4.7.2-runtime
COPY --from=build /app/WcfClient/bin/Debug/ ./